flows:
  - "Tests/Signup/*"
  - "Tests/StaffManagement/*"
  - "Tests/Settings/*"
  - "Tests/Analytics/*"
  - "Tests/Miscellaneous/*"
  - "Tests/Profile/*"

# includeTags:
#   - dev
  # - uat
  # - prod

executionOrder:
    continueOnFailure: true 
    flowsOrder:   
    #Signup
        - Tests/Signup/businessTypeDropdownValidations.yaml
        - Tests/Signup/businessNameTextFieldValidations.yaml
        - Tests/Signup/businessNameTextFieldValidationsLimitedCompany.yaml
        - Tests/Signup/charityNameTextFieldValidations.yaml
        - Tests/Signup/crnTextFieldValidations.yaml
        - Tests/Signup/industryTypeDropdownValidations.yaml
        - Tests/Signup/addressLine1TextFieldValidations.yaml
        - Tests/Signup/addressLine2TextFieldValidations.yaml
        - Tests/Signup/cityTextFieldValidations.yaml
        - Tests/Signup/postCodeTextFieldValidations.yaml
        - Tests/Signup/utrNumberTextFieldValidations.yaml
        - Tests/Signup/websiteTextFieldValidations.yaml
        - Tests/Signup/firstNameTextFieldValidations.yaml
        - Tests/Signup/lastNameTextFieldValidations.yaml
        - Tests/Signup/emailTextFieldValidations.yaml
        - Tests/Signup/accountNumberAndConfirmAccountNumberFieldValidations.yaml
        - Tests/Signup/sortCodeFieldValidations.yaml
    #StaffManagement
        - Tests/StaffManagement/firstNameAndLastNameTextFieldValidations.yaml
        - Tests/StaffManagement/mobileNumberTextFieldValidations.yaml
        - Tests/StaffManagement/emailTextFieldValidations.yaml
        - Tests/StaffManagement/supervisorAddEmployee.yaml
    #Settings
        - Tests/Settings/merchantAbout.yaml
        - Tests/Settings/merchantAppLock.yaml
        - Tests/Settings/merchantHowItWorks.yaml
        - Tests/Settings/merchantVoiceNotificationToggle.yaml
        - Tests/Settings/notesOnBankStatementToggle.yaml
        - Tests/Settings/sandboxApiAccess.yaml
        - Tests/Settings/productionApiAccess.yaml
        - Tests/Settings/merchantLogout.yaml
        - Tests/Settings/cashierAbout.yaml
        - Tests/Settings/cashierAppLock.yaml
        - Tests/Settings/cashierHowItWorks.yaml
        - Tests/Settings/cashierVoiceNotificationToggle.yaml
        - Tests/Settings/cashierLogout.yaml
        - Tests/Settings/supervisorAbout.yaml
        - Tests/Settings/supervisorAppLock.yaml
        - Tests/Settings/supervisorHowItWorks.yaml
        - Tests/Settings/supervisorVoiceNotificationToggle.yaml
        - Tests/Settings/supervisorLogout.yaml
    #Tips
        - Tests/Tips/tipsAmountTextFieldValidations.yaml
        - Tests/Tips/tipsPercentageTextFieldValidations.yaml
        - Tests/Tips/supervisorTipsVerification.yaml
        - Tests/Tips/cashierTipsVerification.yaml
    #Analytics
        - Tests/Analytics/analyticsPageVerificationHomePage.yaml
        - Tests/Analytics/analyticsPageVerificationSideMenu.yaml
    #Miscellaneous
        - Tests/Miscellaneous/merchantSupport.yaml
        - Tests/Miscellaneous/merchantTheme.yaml
        - Tests/Miscellaneous/supervisorSupport.yaml
        - Tests/Miscellaneous/supervisorTheme.yaml
        - Tests/Miscellaneous/cashierSupport.yaml
        - Tests/Miscellaneous/cashierTheme.yaml
    #Profile
        - Tests/Profile/address1TextFieldValidations.yaml
        - Tests/Profile/address2TextFieldValidations.yaml
        - Tests/Profile/cityTextFieldValidations.yaml
        - Tests/Profile/postCodeFieldValidations.yaml
        - Tests/Profile/editBusinessDetails.yaml
        - Tests/Profile/firstNameAndLastNameTextFieldValidations.yaml
        - Tests/Profile/cashierProfileVerification.yaml
        - Tests/Profile/supervisorProfileVerification.yaml
    #HomePage
        - Tests/HomePage/merchantHomePageApprovedKyb.yaml
        - Tests/HomePage/merchantHomePagePendingKyb.yaml
        - Tests/HomePage/supervisorHomePageApprovedKyb.yaml
        - Tests/HomePage/supervisorHomePagePendingKyb.yaml
        - Tests/HomePage/cashierHomePageApprovedKyb.yaml
        - Tests/HomePage/cashierHomePagePendingKyb.yaml
        - Tests/HomePage/merchantSuspendedPageVerification.yaml
        - Tests/HomePage/merchantBlockedPageVerification.yaml
        - Tests/HomePage/merchantFraudulentPageVerification.yaml
        - Tests/HomePage/employeeSuspendedPageVerification.yaml
        - Tests/HomePage/employeeBlockedPageVerification.yaml
        - Tests/HomePage/employeeFraudulentPageVerification.yaml
    #Transactions
        - Tests/Transactions/merchantTransactionsPageVerification.yaml
    #OrderQR
        - Tests/Miscellaneous/orderQRPageWithoutKyb.yaml
        - Tests/Miscellaneous/orderQRPageApprovedKyb.yaml