flows:
  "Tests/Signup/*"

# includeTags:
#   - dev
  # - uat
  # - prod

executionOrder:
    continueOnFailure: true 
    flowsOrder:
    
    #Signup
        - Tests/Signup/businessTypeDropdownValidations.yaml
        - Tests/Signup/businessNameTextFieldValidations.yaml
        - Tests/Signup/businessNameTextFieldValidationsLimitedCompany.yaml
        - Tests/Signup/charityNameTextFieldValidations.yaml
        - Tests/Signup/crnTextFieldValidations.yaml
        - Tests/Signup/industryTypeDropdownValidations.yaml
        - Tests/Signup/addressLine1TextFieldValidations.yaml
        - Tests/Signup/addressLine2TextFieldValidations.yaml
        - Tests/Signup/cityTextFieldValidations.yaml
        - Tests/Signup/postCodeTextFieldValidations.yaml
        - Tests/Signup/utrNumberTextFieldValidations.yaml
        - Tests/Signup/websiteTextFieldValidations.yaml
        - Tests/Signup/firstNameTextFieldValidations.yaml
        - Tests/Signup/lastNameTextFieldValidations.yaml
        - Tests/Signup/emailTextFieldValidations.yaml
        - Tests/Signup/accountNumberAndConfirmAccountNumberFieldValidations.yaml
        - Tests/Signup/sortCodeFieldValidations.yaml