output.idVerificationPage = {
    idVerificationPageTitle: 'ID Verification',
    rejectedTipText1: `The information provided doesn't match your ID. Please try again!`,
    rejectedTipText2: `Verify that the information in your documents matches the details displayed below`,
    personalDetailsTip: 'Make sure the name matches the ID provided.',
    businessDetailsTip: 'Make sure that your business address is the same as in your address proof document',
    businessDetailsTip2: 'Make sure that your address is the same as in your address proof document',
    uploadTile: 'Upload',
    idProof: 'Add ID Proof',
    idProofUploaded: ' ID Proof',
    idProofRejected: 'Re-upload Passport',
    addressProof: 'Add Address Proof',
    addressProofUploaded: ' Address Proof',
    addressProofRejected: 'Re-upload Address Proof',
    selfie: 'Add Selfie',
    selfieUploaded: ' Selfie',
    selfieRejected: '',
    firstNameField: 'First Name* TextFormField',
    firstName: 'First Name*',
    lastNameField: 'Last Name* TextFormField',
    lastName: 'Last Name*',
    businessNameField: 'Business Name* TextFormField',
    businessName: 'Business Name*',
    addressLine1Field: 'Business Address Line 1* TextFormField',
    addressLine1: 'Business Address Line 1*',
    addressLine2Field: 'Business Address Line 2 (Optional) TextFormField',
    addressLine2: 'Business Address Line 2 (Optional)',
    postCodeField: 'Post Code* TextFormField',
    postCode: 'Post Code*',
    dobField: 'Date of Birth* TextFormField',
    dob: 'Date of Birth*',
    incorporationDateField: 'Incorporation Date* TextFormField',
    incorporationDate: 'Incorporation Date*',
    okButton: 'OK',
    submitButton: 'Submit for Verification',
    resubmitButton: 'Resubmit for Verification',
    supportEmail: 'hello@paywithatoa.co.uk',

    idProofDosHeader: `Document Do's and Dont's`,
    idProofDosSubtitle1: 'Good Example',
    idProofDosText1: 'All corners in frame with contents clearly visible',
    idProofDosSubtitle2: 'Bad Examples',
    idProofDosText2: 'Excessive Glare',
    idProofDosText3: 'Cropped Photos',
    idProofDosText4: 'Blurred Photos',
    idProofDosText5: 'ID is too far away',
    
    iUnderstandButton: 'I Understand',

    idProofUploadHeader: 'ID Proof',
    idProofUploadText1: 'Tap your format below and upload a clear copy of your ID',
    passportCheckbox: 'Passport',
    dlCheckbox: 'UK Drivers License or\nUK Biometric Residence Permit',
    uploadPassportButton: 'Upload Passport',
    uploadedPassportButton: ' Passport',
    uploadDlFrontButton: 'Upload License or BRP (Front)',
    uploadedDlFrontButton: ' License or BRP (Front)',
    uploadDlBackButton: 'Upload License or BRP (Back)',
    uploadedDlBackButton: ' License or BRP (Back)',

    addressProofUploadHeader: 'Address Proof',
    addressProofUploadText1: 'Please upload a recent document that clearly shows your name and address you entered in the last screen.\nWe accept the following:\n\n1. Utility bills\n2. Bank statements\n3. Card machine invoices\n4. Council tax receipts',
    addressProofUploadButton: 'Upload Address Proof',
    addressProofUploadedButton: ' Address Proof',
    documentTypeDropdownField: 'null TextFormField',
    documentTypeDropdown: 'Select Document Type',
    docType1: 'Utility bill',
    docType2: 'Bank statement',
    docType3: 'Card machine invoice',
    docType4: 'Council tax receipt',
    addressProofUploadedButton: ' Address Proof',

    selfieDosHeader: `Selfie Do's and Dont's`,
    selfieDosSubtitle1: 'Good Example',
    selfieDosText1: 'Clear view of your face inside\nthe frame  with proper lighting',
    selfieDosSubtitle2: 'Bad Examples',
    selfieDosText2: 'Remove glasses',
    selfieDosText3: 'Use proper lighting',

    addDocumentsButton: 'Add Documents',

    firstNameEmptyError: 'First Name shuld not be empty',
    firstNameBlankSpacesError: 'First Name should not contain only spaces',
    
    lastNameEmptyError: 'Last Name should not be empty',
    lastNameBlankSpacesError: 'Last Name should not contain only spaces',

    businessNameEmptyError: 'Business Name should not be empty',
    businessNameBlankSpacesError: 'Business Name should not contain only spaces',
    businessNameAlreadyExistsToast: 'Merchant with this legal business name already exists',
    businessNameMinLengthError: 'Business Name should be at least 3 characters long',
    businessNameSpecialCharactersError: `Only , & : ' - are allowed`,

    address1EmptyError: 'Business Address Line 1 should not be empty',
    address1BlankSpacesError: 'Business Address Line 1 should not contain only spaces',
    address1SpecialCharactersError: `Only , & : ' - are allowed`,
    address1MinLengthError: 'Business Address Line 1 should be at least 3 characters long',

    address2EmptyError: 'Business Address Line 2 should not be empty',
    address2BlankSpacesError: 'Business Address Line 2 should not contain only spaces',
    address2SpecialCharactersError: `Only , & : ' - are allowed`,
    address2MinLengthError: 'Business Address Line 2 should be at least 3 characters long',

    postCodeEmptyError: 'Post Code should not be empty',
    postCodeBlankSpacesError: 'Post Code should not be empty',
    postCodeSpecialCharactersError: `Post Code is invalid`,
    postCodeMinLengthError: 'Post Code should be at least 3 characters long',
}   