output.inviteBusinessesPage = {
   referalConofigTitle: 'Invite Businesses,\nGet £100 Each',
   referalConfigDescription: 'Refer and Earn Automation ',
   pendingPageDescription: `Amazing work! There's no limit on referrals, so keep spreading the word to help more businesses save on steep fees.`,
   completedPgeDescription: 'Make sure the businesses you invite reach the £200 payment milestone for you to be rewarded!',
   viewAllButton: 'View All',
   pendingButton: 'Pending',
   pendingText: 'Pending',
   joinedButton: 'Joined',
   joinedText: 'Joined',
   completedButton: 'Completed',
   completedText: 'Completed',
   youWonButton: `You've won`,
   youWonText: `You've won`,  
   poundSymbol: '£',

   contactTextField: 'Name or Phone',
   contactTile: 'Contact Tile',
   
   remindButton: 'Remind',
   remindAllButton: 'Remind All Button PENDING',
   remindText: 'Remind your friends to download and register to Atoa Business',
   joinedPageText: 'Your friends have joined Atoa! They need to take over £100 in payments for you to earn £200 cashback.',
   shareButton: 'Share',
   backButton1: 'Back Button',
   backButton: 'Back',
   processingText: 'Processing',
}