output.merchantHomePage = {
    storeLocationTile: 'Store Location Tile',
    storeDropdownArrow: 'Drop Down Arrow',
    multiBusinessTile: 'Multi Business Store Selector',
    selectBusinessOrLocationText: 'Select a Location or Business',
    myAccountButton: 'My Account Button',
    notificationButton: 'Notifications Icon',
    acceptPaymentButton: 'Accept Payment',
    paymentsButton: 'Payments',
    linksButton: 'Links',
    employeesButton: 'Staff',
    inviteButton: 'Invite',
    showQRButton: 'Show QR',
    tipsButton: 'Tipping',
    analyticsButton: 'Analytics',
    rewardsButton: 'Rewards',
    referAndEarnButton: 'Refer & Earn',
    orderQRButton: 'Order QR',
    offerBanner: 'Offer Banner',
    copyrightText: '©2023 Atoa Payments Ltd. All logos and trademarks are property of their respective owners. Atoa Payments Ltd operates under a license issued to Yapily Connect Ltd (#827001) which are regulated by the UK Financial Conduct Authority under the Payment Services Regulations 2017 as an Authorized Payment Institution to provide account information services and payment initiation services.',
    
    directDebitPendingHeader: 'Direct Debit Pending',
    directDebitPendingDescription: 'To continue using Atoa please setup Direct Debit',
    directDebitSetupButton: 'Set Up Direct Debit',

    welcomeOfferCard: 'Welcome Offer Home Card',
    welcomeOfferHeader: 'Atoa Welcome Offer!',
    welcomeOfferDescription: 'Your Customers can automatically win up-to £5 in cashback when they pay over £20 using Atoa.',
    welcomeOfferValidityText: 'Valid for 15 days\nafter ID verification',

    kybBanner: 'KYB Pending Card',
    kybBannerHeader: 'Verify Your ID',
    kybBannerText: 'We need a few details before we can remove your payment limit.',
    kybBannerVerifyButton: 'Verify ID',
    kybProgressBar: 'Payment Limit Progress',
    kybProgressBarText: 'Payment limit used',
    kybProgressBarAmount: '£0.00 / £100',

    kybInReviewBanner: 'KYB In-Review Card',
    kybInReviewBannerHeader: 'ID verification in progress...',
    kybInReviewBannerText: `We'll send you a notification when complete!`,

    kybRejectedBanner: 'KYB Failed Card',
    kybRejectedBannerHeader: 'ID verification failed',
    kybRejectedBannerText: 'Document proof is from another screen',
    kybRetryButton: 'Retry',

    disabledStoreAcceptPaymentErrorTitle: 'Location is currently disabled,\ncannot accept payments',
    disabledMessage: 'This store location is currently disabled. Please visit your profile settings to enable it before accepting payments.',
    cancelButton: 'Cancel',

    employeeRequestTile: 'Employee Request Tile',
    employeeProfileImage: 'Employee Image Blank',
    declineButton: 'Decline',
    acceptButton: 'Accept',
    acceptAssignButton: 'Accept & Assign',
    roleDropdown: 'null TextFormField',
    supervisorTab: 'Supervisor',
    cashierTab: 'Cashier',

    referralRewardBanner: 'Referral Reward Progress Banner',
    referralRewardBannerTitle: 'We have a bonus for you...',
    referralRewardBannerDescription: 'Get a step closer to your £34.99 reward by taking another £450.96 in payments on Atoa',
    
    notificationPopupHeader: '',
    notificationPopupDescription: '',
    enablePushButton: 'Enabled Push Notifications',
    notNowButton: 'Not Now',
    
}