output.settingsPage = {
    backButton: 'Back button',
    settingsPageTitle: 'Settings',
    directDebitBanner: 'Set Up',
    appLockToggle: 'App Lock Tile Custom Switch',
    pinTextField: 'App lock pin input',
    logoutButton: 'Log Out',
    confirmButton: 'Confirm',
    voiceNotificationToggle: 'Voice Notification Tile Custom Switch',
    howItWorksTab: 'How it Works',
    apiAccess: 'API Access',
    integrations: 'Integrations',
    noteOnBankStatement: 'Notes on Bank Statements',
    about: 'About',

    incorrectPinToast: 'Incorrect PIN. Try again.',

    directDebitPendingHeader: 'Direct Debit Pending',
    directDebitPendingDescription: 'To continue using Atoa please setup Direct Debit',
    directDebitSetupButton: 'Set Up Direct Debit',

    nextButton: 'Next',
    finishButton: 'Finish',
    hiw1: 'Enter the amount your customer owes and add a note if you like',
    hiw2: 'Ask the customer to scan the QR code using their phone camera or Atoa Pay',
    hiw3: `This will trigger a payment in the customer's banking app for approval`,
    hiw4: `A 'kerching!' lets you both know payment is complete – funds settled to you in seconds!`,

    integrationsTile: 'Integration Platform Card',
    integration1: 'Keyloop',
    integration2: 'Point One',
    integration3: 'Till Tech',
    integration4: 'Epos Now',
    integration5: 'Xero Invoicing',

    pointOneCompanyIdField: 'Company ID* TextFormField',
    pointOneSiteIdField: 'Site ID* TextFormField',
    apiKeyField: 'API Key* TextFormField',
    continueButton: 'Continue',
    doneButton: 'Done',
    deleteIntegrationButton: 'Delete Integration',
    deleteButton: 'Delete',

    scanTillTechQrButton: 'Scan Till Tech QR',
    linkManuallyButton: 'Link Manually',
    urlField: 'URL TextFormField',
    finishButton: 'Finish Linking',
    invalidUrlToast: 'URL is invalid',

    noteOnBankStatementTitle: 'Notes on Bank Statements',
    noteOnBankStatementToggle: 'Use Notes As Bank Payment Ref Switch',
    notesDescription1: 'Make your bank statements easier to reference with personalised notes. You can enable or disable this feature at any time on the slider below.',
    notesText: 'Add notes to your bank statements?',

    privacyPolicyTab: 'Privacy Policy',
    privacyPolicyTitle: 'Atoa Business Privacy Policy',
    termsOfUseTab: 'Terms of Use',
    termsOfUseTitle: 'Platform Terms of Use',
    termsOfServiceTab: 'Terms of Service',
    termsOfServiceTitle: 'Terms of Service (for Consumers & Merchants)',
    aboutAppTab: 'About app', 
    aboutAppTitle: 'Atoa Business',


}