output.yourBusinessDetailsPage = {
    businessTypeDropDownTile: 'Business Type* TextFormField',    
    businessType: 'Business Type*',
    soleTrader: 'Sole Trader',
    limitedCompany: 'Limited Company',
    charity: 'Charity',
    
    businessNameField: 'Business Name* TextFormField',
    businessName: 'Business Name*',
    charityNameField: 'Charity Name* TextFormField',
    charityName: 'Charity Name*',

    crnField: 'Company Registration Number* TextFormField',
    crn: 'Company Registration Number*',
    charityNumberField: 'Charity Number* TextFormField',
    charityNumber: 'Charity Number*',

    industryTypeDropdown: 'Select Industry* TextFormField',
    industryType: 'Select Industry*',
    industryTypeSearchBoxField: 'null TextFormField',
    industryTypeSearchBox: 'Search Industry',
    industry1: 'Accommodation',
    industryNotFoundText: 'No results found!',
    describeYourBusinessField: 'Describe your business* TextFormField',
    addressLine1Field: 'Address Line 1* TextFormField',
    addressLine1: 'Address Line 1*',
    addressLine2Field: 'Address Line 2 (Optional) TextFormField',
    addressLine2: 'Address Line 2 (Optional)',
    cityField: 'Town/City* TextFormField',
    city: 'Town/City*',
    postCodeField: 'Post Code* TextFormField',
    postCode: 'Post Code*',
    utrField: 'UTR Number (Optional) TextFormField',
    utr: 'UTR Number (Optional)',
    websiteField: 'Website URL (Optional) TextFormField',
    website: 'Website URL (Optional)',
    vat: 'VAT TextFormField',
    vatText: 'VAT',
    vatToggle: 'VAT Custom Switch',
    vatOptionsTitle: 'Tax charges (%)',
    vatOption1: '0.0',
    vatOption2: '5.0',
    vatOption3: '20.0',
    serviceCharge: 'Service Tax TextFormField',
    serviceChargeText: 'Service Tax',
    serviceChargeToggle: 'Service Tax Custom Switch',
    turnoverDropdown: 'Average monthly turnover* TextFormField',
    turnover: 'Average monthly turnover*',
    continueButton: 'Continue',

    businessNameEmptyError: 'Please provide a business name',
    businessNameSpecialCharactersError: 'Special characters are not allowed',
    businessNameMinLengthError: 'Business Name should be at least 3 characters long',
    businessNameExistingError: 'Merchant with this legal business name already exists',

    limitedBusinessNameEmptyError: 'Please provide a company name',
    limitedBusinessNameMinLengthError: 'Company namme should be at least 3 characters long',
    limitedBusinessNameSpecialCharactersError: 'Special characters are not allowed',

    charityNameEmptyError: 'Please provide a charity name',
    charityNameSpecialCharactersError: 'Special characters are not allowed',
    charityNameMinLengthError: 'Charity Name should be at least 3 characters long',
    charityNameExistingError: 'Merchant with this legal business name already exists',

    crnEmptyError: 'Please provide a company number',
    crnMinLengthError: 'Company Registration Number is invalid',
    crnExistingError: 'Merchant with this CRN number already exists',

    invalidIndustryTypeError: 'No results found!',

    addressLine1EmptyError: 'Please enter the first line of your address',
    addressLine1SpecialCharactersError: `Only , & : ' - are allowed`,
    addressLine1MinLengthError: 'Address Line 1 should be at least 3 characters long',

    addressLine2EmptyError: 'Please enter the second line of your address',
    addressLine2SpecialCharactersError: `Only , & : ' - are allowed`,
    addressLine2MinLengthError: 'Address Line 2 should be at least 3 characters long',
    
    cityEmptyError: 'Please enter your town or city',
    citySpecialCharactersError: `Only , & : ' - are allowed`,
    cityMinLengthError: 'Town/City should be at least 3 characters long',

    postCodeEmptyError: 'Please provide a post code',
    postCodeSpecialCharactersError: 'Post Code is invalid',
    postCodeMinLengthError: 'Post Code should be at least 3 characters long',

    emptyVATError: `Deactivate VAT if you haven't applied any VAT.`,
    serviceChargeMoreThan100Error: 'Service charges should not be more than 100%',
    emptyServiceChargeError: `Turn off service charges if you don't include any service charge.`,

    describeBusinessMinLengthError: 'Your business description should be at least 5 characters long',
    describeBusinessEmptyError: 'Briefly outline what your business does',

    utrMinLengthError: 'UTR needs to be minimum 10 digits',
    utrExistingError: 'UTR already registered. Try again with a unique number',

    websiteInvalidError: 'Check URL format and retry',

    closeAddBusinessHeader: 'Are you sure you want to leave now?',
    closeAddBusinessDescription: '',
    keepButton: 'Keep',
    discardButton: 'Discard',
}